name: screens-app
recipe: laravel
config:
  webroot: ./public


build_as_root:
    # Note that you will want to use the script for the major version of node you want to install
    # See: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
    - curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - apt-get install -y nodejs

services:
  myservice:
     type: php:7.3
     via: apache:2.4
     ssl: true
  node:
    type: node
    build:
      - npm install


tooling:
  npm:
    service: node
  node:
    service: node
  abracadabra:
    service: appserver
    description: my custom installation.
    cmd:
      - composer install
      - cp .env.example .env
      - php artisan key:generate
      - cd resources/frontend/app/
      - npm i
      - npm run serve
